name: weather_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  weather_icons: ^3.0.0
  gap: ^3.0.1
  intl: ^0.19.0
  sticky_headers: ^0.3.0+2
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  get_storage: ^2.1.1
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1
  flutter_dotenv: ^5.1.0
  logger: ^2.3.0

dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

